### PR TITLE
Check the existence of min and max explicitly to avoid problems with falsy values

### LINKED ISSUE #97: Constraint validation in input component fail when the constraint equals 0
In input.component.ts, expressions of the form `if (this.min && value < this.min)` fail when the constraint (in this case, `min`) equals 0 as `0 && <boolean>` always resolves to `false` because `0` is a falsy value.

### PR DESCRIPTION
**Pull request by JavierCenteno**
Fix #97

### CODE REVIEW

File: projects/lux/src/lib/input/input.component.ts [hunk 1]
```diff
@@ -217,15 +217,15 @@ export class InputComponent implements OnInit, ControlValueAccessor, Validator {
       this.type === 'time' ||
       this.type === 'timestamp'
     ) {
-      if (this.min && value < this.min) {
+      if (this.min !== undefined && value < this.min) {
```
Comment (pjmolina) [inline projects/lux/src/lib/input/input.component.ts:220]: need to check also for null.

File: projects/lux/src/lib/input/input.component.ts [hunk 2]
```diff
@@ -217,15 +217,15 @@ export class InputComponent implements OnInit, ControlValueAccessor, Validator {
...
         result = result || {};
         result.min = {
           value,
           min: this.min,
           reason: `Value is lower than minimum value: ${this.min}.`
         };
       }
-      if (this.max && value > this.max) {
+      if (this.max !== undefined && value > this.max) {
```
Comment (pjmolina) [inline projects/lux/src/lib/input/input.component.ts:228]: idem (null check missing)

**Review by pjmolina — CHANGES_REQUESTED** [review]
null checks

**Review by pjmolina — APPROVED** [review]
looks good to me
